# Generated by Django 2.1.7 on 2019-04-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_guest_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='attention',
            new_name='attendance',
        ),
    ]
