# Generated by Django 2.1.7 on 2019-04-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190406_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='attendance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
