# Generated by Django 2.1.7 on 2019-04-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190406_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
